import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import { Toaster } from "sonner";
import GoUpButton from "../../components/GoUpButton";
import Footer from "../../components/Footer";

const nunito = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased relative`}>
        <Navbar />
        <main className="max-md:mx-6">{children}</main>
        <Toaster position="top-center" />
        <GoUpButton />
        <Footer />
      </body>
    </html>
  );
}
